# SPDX-FileCopyrightText: Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0

name: Template Repo Sync

on:
  # allow manual runs
  workflow_dispatch:

  # enable this workflow to be reused
  workflow_call:

jobs:
  sync-with-template-repo:
    name: Sync with template repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Try retrieve changes
        uses: zaufi/sync-with-template-repo-action@master
        with:
          token: ${{ github.token }}
